### ISSUE TITLE
Need help to change file name & audio recording 

### ISSUE THREAD

**Issue by jackaru** [uestccokey/EZFilter#14]
I want to change file name/camera filter/audio state, after Pipeline is already setted on openCamera function

```
//Setup camera
        mRenderPipeline = EZFilter.input(mCamera, mCamera.getParameters().getPreviewSize())
                .enableRecord(Environment.getExternalStorageDirectory() + "/" + Environment.DIRECTORY_DCIM + "/FilterApp/" + timeStamp + ".mp4", true, mAudioState)
                .addFilter(new TestFilter())
                .into(mRenderView);
```

That's ok. With this code I build the Pipeline for the first time on the app on openCamera private void. But the problem is if I change the Pipeline before startRecording on startRecording private void: to rename new file with timestamp or change audio recording to true or false. But all data will be the same of the first Pipeline build so it doesn't take changes.

```
                    mRenderPipeline = EZFilter.input(mCamera, mCamera.getParameters().getPreviewSize())
                            .enableRecord(Environment.getExternalStorageDirectory() + "/" + Environment.DIRECTORY_DCIM + "/FilterApp/" + timeStamp + ".mp4", true, mAudioState)
                            .addFilter(new TestFilter())
                            .into(mRenderView);
                    startRecording();
```

How can I solve this?

**Comment by jackaru** [comment]
I see that is possible only to change filters on Pipeline, I hope you implements the possibility of changing file name and audio recording boolean soon as possible!

**Comment by uestccokey** [comment]
ok，that's easy，i will write it tomorrow
