### ISSUE TITLE
Bitmap: animated filters

### ISSUE THREAD

**Issue by jackaru** [uestccokey/EZFilter#16]
I note that in Bitmap, animated filters doesn't work, returning a static filtered image.
If it's possible, make they works to record them will be a cool feature :)

**Comment by uestccokey** [comment]
I will think about it

**Comment by uestccokey** [comment]
It should have been supported.
You can simply use the following code
`mRenderView.setRenderMode(GLTextureView.RENDERMODE_CONTINUOUSLY);`
to support picture recording.
See demo
