### ISSUE TITLE
Low quality for higher FPS

### ISSUE THREAD

**Issue by jackaru** [uestccokey/EZFilter#18]
I was testing my new shader that requires a big amount of GPU with very low camera FPS

https://pastebin.com/Up7wnUDZ (if you wanna try) 

Is there a way on Android opengles of decrease rendering texture quality to boost FPS? Can you implement that option if there's a way?

**Comment by uestccokey** [comment]
The simplest way to get a high Fps is to use the following code
`mRenderView.setRenderMode(GLTextureView.RENDERMODE_CONTINUOUSLY);`
But it will increase the power consumption of mobile phones.
What's the FPS you have tested? I think it's good if it's greater than 15

**Comment by jackaru** [comment]
@uestccokey It's increasing FPS like a charm, now they're like 10/15 thanks!
There aren't other options like quality?

**Comment by uestccokey** [comment]
In your example, you don't use extra textures, the only texture comes from the camera, so you can improve the FPS by reducing the preview size. 
I don't know how to improve FPS by reducing texture quality.
