### ISSUE TITLE
Find drawable path string

### ISSUE THREAD

**Issue by jackaru** [uestccokey/EZFilter#19]
I've tried many method to get path of my "noise.png" drawable for inputImage2 but no one works, can you explain me how to get it? Thanks in advance :)
![image](https://user-images.githubusercontent.com/21238513/34083986-908bcb90-e379-11e7-9846-743f730b1bdf.png)

**Comment by uestccokey** [comment]
`BitmapUtil.Scheme.DRAWABLE.wrap("" + R.drawable.noise)`
you can see the detail in BitmapUtil.class

**Comment by jackaru** [comment]
Gives me another error, "Invalid int.."
![image](https://user-images.githubusercontent.com/21238513/34127593-02fa9ad4-e43e-11e7-98a8-3faee91abf99.png)

**Comment by uestccokey** [comment]
`BitmapUtil.Scheme.DRAWABLE.wrap("" + R.drawable.noise)`
not
`BitmapUtil.Scheme.DRAWABLE.wrap("drawable://" + R.drawable.noise)`

**Comment by uestccokey** [comment]
you can see the detail in BWRender.class

**Comment by jackaru** [comment]
Thanks for answer, I had left the "Drawable://" from the details :sob: now it's working well.
I'm devouring your api so, did you plan to add the "touch position" in the view? It will be interesting for certain type of filters

**Comment by uestccokey** [comment]
What's "touch position" used to do

**Comment by jackaru** [comment]
It can be used to manipulate some coordinates like this example:
https://www.shadertoy.com/view/Ml2yDy 
You'll be able to adjust rotation with mouse.x & the amount with mouse.y

Also a more important and useful integration in the code will be a support to output multiple frag shaders:
Retro gameboy: https://www.shadertoy.com/view/4tc3Wr
VHS: https://www.shadertoy.com/view/MdffD7

Ref to another post with explanation:
> https://github.com/patriciogonzalezvivo/glslViewer/issues/65

**Comment by uestccokey** [comment]
"touch position" is not a common feature, so the library will not contain it, But I will implement it in demo later.

About the "multiple frag shaders", If the processing is serial, you can implement this feature by adding multiple filters.
Such as:
`EZFilter.input(xxx)
                .addFilter(new BWRender(this), 0.5f)
                .addFilter(new WobbleRender())
                .into(view)`

**Comment by jackaru** [comment]
Seems working, the inputTextureCoordinate in the second shader return the first shader output and that's what I was trying to do! 
In shadertoy there is a uniform vec3 iResolution (viewport resolution in pixel), how can I get it? I need it to stretch the uv of the first shader output to screen size
https://www.shadertoy.com/view/MdffD7
![image](https://user-images.githubusercontent.com/21238513/34447817-cee4e300-ece7-11e7-8c8b-50f62304250d.png)

**Comment by uestccokey** [comment]
Happy New Year!

We can't get iResolution directly, but we can pass the screen width and height into it.
such as
<img width="569" alt="c5994167-c245-4fa8-bc14-d13e55f700b4" src="https://user-images.githubusercontent.com/7234924/34465511-080a4cba-eeeb-11e7-95a6-bbcb3205024f.png">
in BWRender.class

**Comment by jackaru** [comment]
Happy new year !
I made it but is the wrong method, couse the render view doesn't fit the screen in my app. I need to pass the rendering view x/y, how can I get them?

**Comment by jackaru** [comment]
![image](https://user-images.githubusercontent.com/21238513/34682891-a973dbba-f4a0-11e7-9b7b-806d3cc8a63e.png)
Works!
