### ISSUE TITLE
Video importing orientation

### ISSUE THREAD

**Issue by jackaru** [uestccokey/EZFilter#21]
Found an issue when importing a video to renderview, the mediaplayer doesnt work with video orientation: because when I import a video in landscape it works well, if is in potrait it will stretch.

![screenshot_20180115-230308](https://user-images.githubusercontent.com/21238513/34963859-03443086-fa4b-11e7-8c7c-5af5b20dc0c1.png)

Don't know if it's a non implemented feature or I missed something in my code, here it is:

![image](https://user-images.githubusercontent.com/21238513/34963644-f272acd4-fa49-11e7-9428-e5fd43653fbf.png)
![image](https://user-images.githubusercontent.com/21238513/34963734-64ba95f4-fa4a-11e7-8d85-525c3f981334.png)

**Comment by uestccokey** [comment]
Can you upload this rotated video? I'll test it

**Comment by jackaru** [comment]
https://docs.google.com/uc?export=download&id=1XRzcu8m3umMHbnSYeJikahvXvKz9XJVE

**Comment by uestccokey** [comment]
ok,I fix it.

**Comment by jackaru** [comment]
@uestccokey Errors when I run the app
![image](https://user-images.githubusercontent.com/21238513/35127823-fd62c90a-fcb3-11e7-9b9e-159ff46ad3da.png)

**Comment by jackaru** [comment]
Solved after adding

compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
    }

Thanks for fixing orientation!

**Comment by uestccokey** [comment]
find another bug, i will fix it later.

**Comment by uestccokey** [comment]
oh,it's my player's bug
