### ISSUE TITLE
Compatibility errors

### ISSUE THREAD

**Issue by jackaru** [uestccokey/EZFilter#24]
**I've seen that in some devices tested by google play console, the app will crash only if he choose a filter that include double filters rendering.**

![image](https://user-images.githubusercontent.com/21238513/35170408-7016ed62-fd60-11e7-929c-443b79cf4898.png)

**"no main() in shader", but it exist**

**I don't know where is the problem 'cause is not the android version as you can see**

![image](https://user-images.githubusercontent.com/21238513/35170542-f0bfbf8e-fd60-11e7-893f-97dc28a77758.png)

**Comment by uestccokey** [comment]
can you share you shader?I can test in my pixel

**Comment by jackaru** [comment]
gba1: https://pastebin.com/H0Ze08H8
gba2: https://pastebin.com/HQRN3845
And 
`mRenderPipeline.addFilterRender(new gba1());
mRenderPipeline.addFilterRender(new gba2());`

**Comment by uestccokey** [comment]
I have test your shader in my pixel, find the same error "ERROR: 0:13: '8.' : Syntax error:  syntax error".
so i change the shader
`
                        "const vec4 color1 = vec4(008. / 255., 025. / 255., 032. / 255., 1.);\n" +
                        "const vec4 color2 = vec4(050. / 255., 106. / 255., 079. / 255., 1.);\n" +
                        "const vec4 color3 = vec4(137. / 255., 192. / 255., 111. / 255., 1.);\n" +
                        "const vec4 color4 = vec4(223. / 255., 246. / 255., 208. / 255., 1.);\n" +`
to
`
                        "const vec4 color1 = vec4(8. / 255., 025. / 255., 032. / 255., 1.);\n" +
                        "const vec4 color2 = vec4(050. / 255., 106. / 255., 079. / 255., 1.);\n" +
                        "const vec4 color3 = vec4(137. / 255., 192. / 255., 111. / 255., 1.);\n" +
                        "const vec4 color4 = vec4(223. / 255., 246. / 255., 208. / 255., 1.);\n" +`
then find the similar error "ERROR: 0:14: '9.' : Syntax error:  syntax error"
so i change the shader to
`
                        "const vec4 color1 = vec4(8. / 255., 025. / 255., 032. / 255., 1.);\n" +
                        "const vec4 color2 = vec4(050. / 255., 106. / 255., 79. / 255., 1.);\n" +
                        "const vec4 color3 = vec4(137. / 255., 192. / 255., 111. / 255., 1.);\n" +
                        "const vec4 color4 = vec4(223. / 255., 246. / 255., 208. / 255., 1.);\n" +`
then it can work.
so i think 008 and 079 it's erroneous octal numbers.
When the number begins with 0, some mobile phones use the whole number as an octal number

**Comment by jackaru** [comment]
Thanks, you helped me a lot since I'm still a learner with shaders, I will test it in Google Console if it's working with all devices.
Another micro issue is why is unsupported to take photo or video with a saved video by the app?

**Comment by uestccokey** [comment]
take photo or video with a saved video？
you can see the VideoFilterActivity.java in develop branch, should be supported,

**Comment by jackaru** [comment]
Yah, I missed something with photo that says me "unsupported" and already solved it, but with an imported video I can't use startRecording and stopRecording functions.. I'm alright?

**Comment by uestccokey** [comment]
why? RenderPipeline always has startRecording and stopRecording functions.you say you can't, is it mean will crash?

**Comment by uestccokey** [comment]
`mRenderPipeline = EZFilter.input(mCurrentUri)
                        .addFilter(new BWRender(VideoFilterActivity.this))
                        .enableRecord("/sdcard/recordVideo.mp4", true, false)
                        .setPreparedListener(new IMediaPlayer.OnPreparedListener() {
                            @Override
                            public void onPrepared(IMediaPlayer var1) {
                                Log.e("VideoFilterActivity", "onPrepared");
                            }
                        })
                        .setCompletionListener(new IMediaPlayer.OnCompletionListener() {
                            @Override
                            public void onCompletion(IMediaPlayer var1) {
                                Log.e("VideoFilterActivity", "onCompletion");
                            }
                        })
                        .into(mRenderView);`
I have test in demo, it can work

**Comment by jackaru** [comment]
Yes I mean it will crash, now recording pipeline isn't crashing only after the video is ended with the static image...

**Comment by jackaru** [comment]
Thanks, but I don't know why but it's working only with WhatsApp videos, camera videos is crashing every time with this code

`new Thread() {
                        public void run() {
                            mRenderPipeline = EZFilter.input(Uri.parse(paths.get(0)))
                                    .setLoop(true)
                                    .enableRecord(getPath(1), true, true)
                                    .setPreparedListener(var1 -> Log.e("VideoFilterActivity", "onPrepared"))
                                    .setCompletionListener(var1 -> Log.e("VideoFilterActivity", "onCompletion"))
                                    .into(mRenderView);
                        }
                    }.start();`

**Comment by jackaru** [comment]
Error.
![image](https://user-images.githubusercontent.com/21238513/35333280-74f4cb04-010e-11e8-9e40-0a187c0843bc.png)

**Comment by jackaru** [comment]
Update: is not working only with vertical orientation camera videos

**Comment by uestccokey** [comment]
what's the width and height of camera videos?

**Comment by jackaru** [comment]
1920 x 1080
