### ISSUE TITLE
Purpose of EndPointRender ?

### ISSUE THREAD

**Issue by aminm2a** [uestccokey/EZFilter#25]
A question certainly from a newbie. As I see in the code there are 2 renders: a starting point render (FBORender) and an ending point render (EndPointRender). What is the idea behind EndPointRender ? does it enables you to record ?

**Comment by aminm2a** [comment]
I see, you have used FBO to process (apply filters) the frames right ?

**Comment by uestccokey** [comment]
yes, you can see detail in FBORender
