### ISSUE TITLE
Showing black screen only in View recording

### ISSUE THREAD

**Issue by mangoxxx** [uestccokey/EZFilter#29]
When i add videoview in GLLinearLayout to record particular view and then only audio is working for video being displayed in videoview But video is not visible only it is showing black screen

 <cn.ezandroid.ezfilter.view.glview.GLLinearLayout
        android:id="@+id/gl_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@android:color/white"
        android:layout_centerInParent="true">

        <VideoView
            android:id="@+id/render_view_1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:layout_gravity="center"/>

    </cn.ezandroid.ezfilter.view.glview.GLLinearLayout>

Can you please check So i can record view while playing video

**Comment by uestccokey** [comment]
ok, i will see

**Comment by uestccokey** [comment]
VideoView does not support recording because it is not drawn by Canvas.

**Comment by uestccokey** [comment]
If you want to record video, you can refer to the VideoFilterActivity class in demo.

**Comment by mangoxxx** [comment]
i am trying to blend multiple videos on each other and record the complete view. How is this possible?

**Comment by mangoxxx** [comment]
can you please provide example for blending or overlaying multiple videos on each other with alpha setting

**Comment by uestccokey** [comment]
It's not too clear what you want. what app have this function?

**Comment by mangoxxx** [comment]
https://play.google.com/store/apps/details?id=com.zlogic.glitchfx

Check this app, I need to overlay fx on video with opacity

**Comment by uestccokey** [comment]
oh, i know you want. 
it's very easy, first you can achieve the same effect by adding dynamic stickers on the video, just like SnowStickerRender.
second, you can see MultiVideoInputActivity on the develop branch, i just wrote an example that use glitchfx's effect video.
