### ISSUE TITLE
请问在运行时如何切换滤镜

### ISSUE THREAD

**Issue by ZacharyTech** [uestccokey/EZFilter#3]
你好，若是我有多个滤镜需要在运行时切换，请问该如何做？

**Comment by uestccokey** [comment]
很简单，所有的into(view)操作会获得一个渲染管道对象，比如：
RenderPipeline pipeline  = EZFilter.input(bitmap)
        .addFilter(filter)
        .into(view);
使用pipeline可以新增和删除滤镜，因此需要切换滤镜时，首先调用pipeline的removeFilterRender去掉之前添加的滤镜，然后使用addFilterRender方法添加新滤镜即可。

**Comment by uestccokey** [comment]
@ZacharyTech

**Comment by ZacharyTech** [comment]
好的，谢谢！

**Comment by ZacharyTech** [comment]
这样做可以切换滤镜，不过就是在切换的时候会黑屏一下！

**Comment by uestccokey** [comment]
我马上测试下

**Comment by uestccokey** [comment]
测试了下切换BWRender和WobbleRender没有发现黑屏，等下试试你的LutRender

**Comment by ZacharyTech** [comment]
![](http://lize.tech/Splash.gif)
切换时闪黑屏

**Comment by uestccokey** [comment]
可以看看你切换滤镜的代码吗？
我试了下LutRender切换没发现黑屏
                if (mCurrentRender == mLutRender) {
                    mCurrentRender = mLutRender2;
                    mRenderPipeline.removeFilterRender(mLutRender);
                    mRenderPipeline.addFilterRender(mLutRender2);
                } else {
                    mCurrentRender = mLutRender;
                    mRenderPipeline.removeFilterRender(mLutRender2);
                    mRenderPipeline.addFilterRender(mLutRender);
                }

**Comment by uestccokey** [comment]
@ZacharyTech

**Comment by ZacharyTech** [comment]
抱歉，是我理解错误了，我在切换滤镜的时候重新创建了`RenderPipeline`，导致了黑屏的出现！  非常感谢您的帮助！
