### ISSUE TITLE
Crash when start recording after switched camera

### ISSUE THREAD

**Issue by jackaru** [uestccokey/EZFilter#38]
First of all, I really liked these new features, but I'm having a crash issue when use function "startRecord()" after switching the camera using "switchCamera()" function.
It doesn't matter where the camera is facing at, it doesn't allow to use "startRecording()" after switching camera.
But without using the function, it's working well.
The app is using landscape mode setted under manifest (Maybe this is the problem?)

`
    private void switchCamera() {
        try {
            mCurrentCameraId = (mCurrentCameraId + 1) % Camera.getNumberOfCameras();
        } catch (Exception e){
            Toast.makeText(this, "Can't switch camera", Toast.LENGTH_LONG).show();
        }
        releaseCamera();
        openCamera(mCurrentCameraId);
    }`

https://pastebin.com/YE8jAqzx

**Comment by uestccokey** [comment]
do you mean?
```
...
switchCamera();
startRecording();
...
```
I test it in CameraFilterActivity, there was no crash.
can you try new version 2.0.8?
