### ISSUE TITLE
Webview Issue in ViewFilter Activity

### ISSUE THREAD

**Issue by iapp123** [uestccokey/EZFilter#41]
I am using ViewFilter Activity and In that i am using same WebView and When i am trying to play video in webview and it is not playing video in webview 

 glLayout.post(new Runnable() {
            @Override
            public void run() {
                mRenderPipeline = EZFilter.input(glLayout)
                        .enableRecord("/sdcard/recordView.mp4", true, false)
                        .into(renderView);
                for (GLRender render : mRenderPipeline.getEndPointRenders()) {
                    if (render instanceof ISupportRecord) {
                        mSupportRecord = (ISupportRecord) render;
                    }
                }
            }
        });

When i comment above code it will play my video in webview 

And in webview i am using
    webView.setBackgroundColor(getResources().getColor(R.color.app_blue));
        webView.getSettings().setMediaPlaybackRequiresUserGesture(false);
        webView.getSettings().setJavaScriptEnabled(true);
        webView.getSettings().setJavaScriptCanOpenWindowsAutomatically(true);
        webView.getSettings().setPluginState(WebSettings.PluginState.ON);
        webView.getSettings().setLoadWithOverviewMode(true);
        webView.getSettings().setUseWideViewPort(true);
        webView.setWebViewClient(new WebViewClient() {
            public void onPageFinished(WebView view, String url) {
                Log.e("Here=", "onPageFinished");
                view.loadUrl("javascript:(function() { document.getElementsByTagName('video')[0].play(); })()");
            }
        });
        webView.setWebChromeClient(new WebChromeClient());
       webView.loadUrl("http://13.59.109.107/pixabay/videos/10276_1500364486.mp4");

Please let me know How can i play this video in webView ??

I need same functionality in my project

Please help me for this asap

**Comment by iapp123** [comment]
Hello , I am waiting for your reply .Please make it asap.I really need this functionality running in my project.

**Comment by uestccokey** [comment]
Why do you play video with WebView? You should use VideoInput.

**Comment by iapp123** [comment]
I want to record video with text animations..that' why i am playing video in webview
