### ISSUE TITLE
issue in stopRecording 

### ISSUE THREAD

**Issue by iapp123** [uestccokey/EZFilter#42]
When i start recording  a view in ViewFilter Activity then It is giving me issues while i try to stop recording.
E/ACodec: [OMX.Exynos.AVC.Encoder] Unable to configure for node (err -22)
E/ACodec: [OMX.Exynos.AVC.Encoder] onCreateInputSurface returning error -22

Can you please help me with this.

**Comment by iapp123** [comment]
Please reply asap...I am waiting for your reply

**Comment by uestccokey** [comment]
Can error reappear in demo?
You should provide more information, for example, your code.
