### ISSUE TITLE
can i pause render pipleline or pause video recording ?

### ISSUE THREAD

**Issue by patelmanthan777** [uestccokey/EZFilter#44]
Currently in this project we can start and stop recording but is their any way to pause and resume recording?

**Comment by uestccokey** [comment]
No support for pause and resume. Maybe you want to achieve segmented recording, you can use start and stop, and then merge each generated small file. The advantage is that it is very simple to implement the delete segmentation function.

**Comment by magnusmartin111** [comment]
i can use ffmpeg for merge segment but do you have any inbuilt method in your code for merge video faster then ffmpeg. because ffmpeg takes time.

**Comment by patelmanthan777** [comment]
Then good i will do that. And it is very good and very fast library for recording video with filters. I appreciate you work. Can you give me your contact where you active for any question regarding video processing in future.

**Comment by uestccokey** [comment]
397093109@qq.com
