### ISSUE TITLE
Question on OpenCL

### ISSUE THREAD

**Issue by udexon** [uestccokey/EZFilter#46]
I saw your question on OpenCL on another repo https://github.com/gcp/leela-zero/issues/1679 

I have been trying to find examples of OpenCL on Android -- but so far not very promising. 

Do you mind sharing some of your tutorial or code?

您好。

敝姓伍， 马来西亚华人， 祖籍广东。 这是我的领英帐号： https://www.linkedin.com/in/%E4%BC%8D%E6%A8%91%E7%9B%9B-%E5%8D%9A%E5%A3%AB-liang-ng-ph-d-0502822b/

我看到阁下在 Leela 有关 OpenCL 的提问， 并下载了 Ah Q 围棋 及 EZFilter ， 非常佩服。

我花了好几个星期搜寻有关 Android OpenCL 的例子， 结果不是很满意。

不知阁下有没有公开的 Android OpenCL 教程或例子？  我们也可以洽谈咨询的费用。 请通过领英联系。

谢谢。

**Comment by uestccokey** [comment]
抱歉，我对OpenCL也不熟悉，没有相关的例子。你可以在Github上再搜索下。
