### ISSUE TITLE
Is there a problem here?

### ISSUE THREAD

**Issue by chongbo2013** [uestccokey/EZFilter#50]
![TIM截图20190325175203](https://user-images.githubusercontent.com/3191545/54910161-bd03b880-4f26-11e9-93a9-a1325d16d12d.png)
 if ((mBufferInfo.flags & MediaCodec.BUFFER_FLAG_END_OF_STREAM) != 0) {
            mEncoder.signalEndOfInputStream();
            mIsDecoderEOS = true;
            mBufferInfo.size = 0;
        }
Why do you need to end this? mEncoder.signalEndOfInputStream();

**Comment by uestccokey** [comment]
You can test if you don't add this code. I refer to the MediaCodec demo code provided by Google.
