### ISSUE TITLE
SDK support very high

### ISSUE THREAD

**Issue by khacchungory** [uestccokey/EZFilter#58]
Hi, Why library have interface OnFilterRendersChangedListener, this supported starting with android N (24), how to lower min support version. thanks

**Comment by uestccokey** [comment]
https://github.com/uestccokey/EZFilter/blob/46502c1ce8a2bcecbcbad79edcda731a7b305e0b/app/build.gradle#L22

Try adding compileOptions

**Comment by khacchungory** [comment]
Thank for answer, i fixed successfull
