### ISSUE TITLE
How to use OffscreenImage?

### ISSUE THREAD

**Issue by randauto** [uestccokey/EZFilter#70]
Hi, I'm trying to use OffscreenImage, but I can't see anything in the bitmap, it is transparent.
My code is like the below:
`
val bitmapResult = EZFilter.input(resource).output(resource.width, resource.height)
`
where the resource is my image Bitmap, but nothing in the bitmapResult. 
I'm trying to use your ImageFilterActivity.java, but it is the same when I uncomment this code.
`
            // 截图方式一：不需要渲染在到View上便可以滤镜处理输出图像，图像默认宽高为输入图像的宽高
//                Bitmap bitmap = EZFilter.input(mCurrentBitmap)
//                        .addFilter(new LookupRender(ImageFilterActivity.this, R.drawable.langman))
//                        .output();
//                mPreviewImage.setImageBitmap(bitmap);

            // 截图方式二：需要渲染到View上后才能进行截图，图像默认宽高为View显示的宽高
`
CameraFilterActivity.java and CameraFilter2Activity.java take a screenshot is the same up.
I'm using Android 9.
Please help me! Thanks in advance!

**Comment by uestccokey** [comment]
What model phone is it, can you provide that picture? I have tested many devices and have not encountered this problem

**Comment by randauto** [comment]
> What model phone is it, can you provide that picture? I have tested many devices and have not encountered this problem

Yes, I'm using a Samsung S8 Plus phone with Android OS version 9. This is an image I captured from Android Studio when I debug code.
image from camera2 captured, It's good.
![bitmap](https://user-images.githubusercontent.com/6858507/177451396-7c4d21bb-a3c7-498e-ba30-76242669350c.png)

image fromEzfilter rendered
![bitmap2](https://user-images.githubusercontent.com/6858507/177451403-415fbfc2-960e-4ea1-b601-33f8ff5abd6b.png)

Do you want to provide any more information?

**Comment by uestccokey** [comment]
See if the simulator or other devices will also encounter this problem

**Comment by randauto** [comment]
> See if the simulator or other devices will also encounter this problem

Yes, I run on Android Emulator (Pixel 2 API 30) and also encounter this problem.

**Comment by uestccokey** [comment]
It's a little strange. Can you show me your code. I can't see your modification from [https://github.com/randauto/EZFilter](url)

**Comment by randauto** [comment]
I just took your latest source code and ran it, I did not modify anything. I'm not running on the fork source code. Do you use Telegram or any other communication channel? I can show the code on my PC via Teamviewer.

**Comment by uestccokey** [comment]
Oh, sorry, I found the cause of the error. My branch has indeed fixed this problem and has not been merged into the main branch. Now it's ok

**Comment by randauto** [comment]
A little change that I didn't notice while debugging the code. Thank you very much! I have learned a lot from your source code.

**Comment by uestccokey** [comment]
Thank you for your feedback!

**Comment by Mouadabdelghafouraitali** [comment]
@uestccokey I'm facing an issue with **OffscreenImage**, the output is exactly like the input (no filter applied), the issue happened with only one filter, other filters works fine, can you please tell where the issue comes from?

**Comment by uestccokey** [comment]
@Mouadabdelghafouraitali  Can you show me your some code

**Comment by Mouadabdelghafouraitali** [comment]
@uestccokey Thank you so much for the quick reply, here's the full class of that specific filter :

```
    public GlitchSlicesFilter() {
        setFragmentShader("precision highp float;\n" +
                "uniform sampler2D inputImageTexture;\n" +
                "uniform float iTime;\n" +
                "uniform float width;\n" +
                "uniform float height;\n" +
                "uniform float glitchValue;\n" +
                "#define iResolution vec2(width,height)\n" +
                "varying lowp vec2 textureCoordinate;\n" +
                "const float PI = 3.1415926;\n" +
                "\n" +
                "float rand(float n){\n" +
                "    return fract(sin(n) * 56578.88);\n" +
                "}\n" +
                "\n" +
                "\n" +
                "void main()\n" +
                "{\n" +
                "    vec2 textureCoordx = gl_FragCoord.xy/iResolution.xy;\n" +
                "    float maxJ = 0.08;\n" +
                "    float colorOffset = 0.01;\n" +
                "    float blueOffset = -0.025;\n" +
                "    float time = mod(iTime, 0.3* 2.0);\n" +
                "    float amplitude = max(sin(time * (PI / 0.3)),0.0);\n" +
                "    float jitter = rand(gl_FragCoord.y) * 2.0 - 1.0;\n" +
                "    bool needOffset = abs(jitter) < maxJ * amplitude;\n" +
                "    float textureX = textureCoordx.x + (needOffset ? jitter : (jitter * amplitude * glitchValue));\n" +
                "    vec2 textureCoord = vec2(textureX,textureCoordx.y);\n" +
                "    vec4 normalMask = texture2D(inputImageTexture,textureCoord);\n" +
                "    vec4 maskR = texture2D(inputImageTexture,textureCoord + vec2(colorOffset * amplitude,0.0));\n" +
                "    vec4 maskB = texture2D(inputImageTexture,textureCoord + vec2(blueOffset * amplitude,0.0));\n" +
                "    gl_FragColor = vec4(maskR.r,mask.g,maskB.b, normalMask.a);\n" +
                "}");
        this.currentTime = System.currentTimeMillis();
    }
```

**_NOTE: The same filter works fine with OffscreenVideo_**
