### ISSUE TITLE
OffscreenVideo addFilterRender() method is not working

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [uestccokey/EZFilter#71]
Hi,

I'm trying to save a video with the user's selected filter, when I run the below code I got a really weird behavior :

```
OffscreenVideo offscreenVideo = new OffscreenVideo(videoInputPath);
offscreenVideo.addFilterRender(currentFilter);
offscreenVideo.save(videoOutputPath);
```

**The output :** 
Original video : 

![image](https://user-images.githubusercontent.com/24398682/179352902-3c5e2129-6056-44f7-bb19-018c1e4d4b0d.png)

1 - For some reason, the input video change resolution and become smaller in the `RenderView`

![Sans titre](https://user-images.githubusercontent.com/24398682/179352938-33dc554a-ff10-407d-81d8-4051cdc95915.png)

2 - The video saved without any filter on it.

Thank you.

**Comment by uestccokey** [comment]
When rendering off screen, you should re create the filter and then add it, otherwise it will conflict with the filter being used in the screen

**Comment by Mouadabdelghafouraitali** [comment]
@uestccokey Thank you so much, that's exactly what I've done yesterday, I was just waiting for another solution, before closing this issue
